os:
  - linux

language: php

php:
  - '7.1'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 8.9.3
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  
script:
  - vendor/bin/phpunit --coverage-text
  - npm run test
  # - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  # - npm run production
  # - jshint resources/assets/js/modules/*
